version: '3'
volumes:
  data:
networks:
  database:
  web:
  nqueue:
services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:9.6
    volumes:
      # Volume of data:
      - data:/var/lib/postgresql/data
      # Scripts:
      - ./scripts:/scripts 
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - database
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Reverse proxy configuration
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      # App
      - ./app:/app
    working_dir: /app  #container dir.
    command: bash ./app.sh
    networks:
      - database
      - web
      - nqueue
    depends_on:
      - db
      - queue
    environment:
      - DB_NAME=error....
  queue:
    image: redis:3.2
    networks: 
    - nqueue
  worker:
    build: worker
    volumes:
      # Worker
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - nqueue
    depends_on:
      - queue